#!/usr/bin/awk -f

# generated by smpg.awk 2.1

# <description>
function DESCRIPT_INCLUDES() {
return \
"included files:\n"\
}
function DESCRIPT_FSM() {
return \
"fsm rules:\n"\
"defn_start       -> context_arg_type\n"\
"context_arg_type -> context_var_name\n"\
"context_var_name -> unbound_arg_code\n"\
"unbound_arg_code -> on_error_code\n"\
"on_error_code    -> long_name\n"\
"long_name    -> short_name\n"\
"short_name   -> takes_args\n"\
"takes_args   -> handler_code\n"\
"handler_code -> help_code\n"\
"help_code    -> end\n"\
"end          -> long_name | defn_end\n"\
"defn_end -> defn_start\n"\
"\n"\
"'->' is read as 'must be followed by'\n"\
"'|' is read as 'or'"
}
function DESCRIPT() {
	return (DESCRIPT_INCLUDES() "\n" DESCRIPT_FSM())
}
# </description>

# <other>
# <user_exit>
function exit_success() {exit(0)}
function exit_failure() {exit(1)}
# </user_exit>

# <user_error>
function did_err_happen() {
	return _B_err_happened
}
function err_print(msg) {
	_B_err_happened = 1
	set_should_skip_end()
	print_puts_err(sprintf("%s: error: %s", SCRIPT_NAME(), msg))
}
function err_quit(msg) {
	err_print(msg)
	exit_failure()
}
function err_input(msg) {
	err_print(sprintf("%s:%d: %s", FILENAME, FNR, msg))
}
function err_input_quit(msg) {
	err_input(msg)
	exit_failure()
}
# </user_error>

# <user_print>
function print_ind_line(str, tabs) {print_tabs(tabs); print_puts(str)}
function print_ind_str(str, tabs) {print_tabs(tabs); print_stdout(str)}
function print_inc_indent() {print_set_indent(print_get_indent()+1)}
function print_dec_indent() {print_set_indent(print_get_indent()-1)}
function print_tabs(tabs,	 i, end) {
	end = tabs + print_get_indent()
	for (i = 1; i <= end; ++i)
		print_stdout("\t")
}
function print_new_lines(num,    i) {
	for (i = 1; i <= num; ++i)
		print_stdout("\n")
}

function print_set_indent(tabs) {_B_indent_count__ = tabs}
function print_get_indent(tabs) {return _B_indent_count__}
function print_puts(str) {__print_puts(str)}
function print_puts_err(str) {__print_puts_err(str)}
function print_stdout(str) {__print_stdout(str)}
function print_stderr(str) {__print_stderr(str)}
function print_set_stdout(str) {__print_set_stdout(str)}
function print_set_stderr(str) {__print_set_stderr(str)}
function print_get_stdout() {return __print_get_stdout()}
function print_get_stderr() {return __print_get_stderr()}

function __print_set_stdout(f) {_B_fout_ = ((f) ? f : "/dev/stdout")}
function __print_get_stdout() {return _B_fout_ ? _B_fout_ : "/dev/stdout"}
function __print_stdout(str) {__print(str, __print_get_stdout())}
function __print_puts(str) {__print_stdout(sprintf("%s\n", str))}
function __print_set_stderr(f) {_B_ferr_ = ((f) ? f : "/dev/stderr")}
function __print_get_stderr() {return _B_ferr_ ? _B_ferr_ : "/dev/stderr"}
function __print_stderr(str) {__print(str, __print_get_stderr())}
function __print_puts_err(str) {__print_stderr(sprintf("%s\n", str))}
function __print(str, file) {printf("%s", str) > file}
# </user_print>

# <user_utils>
function data_or_err() {
	if (NF < 2)
		err_input(sprintf("no data after '%s'", $1))
}

function name_check(name) {

	if (name != "\\0" && (name in _B_name_check)) {
		err_input(sprintf("name '%s' redefined from line %d",
			name, _B_name_check[name]))
	} else {
		_B_name_check[name] = FNR
	}
}

function enter() {

	out_dir_set(OutDir)

	if (Help) {
		set_should_skip_end()
		print_help()
	}
	if (Version) {
		set_should_skip_end()
		print_version()
	}
	if (ARGC != 2) {
		set_should_skip_end()
		print_use_try()
	}
}

function set_should_skip_end() {_B_should_skip_end = 1}
function get_should_skip_end() {return _B_should_skip_end}
function set_can_end() {_B_can_end = 1}
function get_can_end() {return _B_can_end}

function leave(    _st) {

	if (!did_err_happen() && !get_should_skip_end()) {
		if (!get_can_end())
			err_input_quit(sprintf("%s was not encountered", STM_DEFN_END()))
		else
			main()
	}
}

function save_context_arg_type(context_arg_type) {__context_arg_type_arr__[++__context_arg_type_num__] = context_arg_type}
function get_context_arg_type(num) {return __context_arg_type_arr__[num]}
function save_context_var_name(context_var_name) {__context_var_name_arr__[++__context_var_name_num__] = context_var_name}
function get_context_var_name(num) {return __context_var_name_arr__[num]}
function save_unbound_arg_code(unbound_arg_code) {__unbound_arg_code_arr__[++__unbound_arg_code_num__] = unbound_arg_code}
function get_unbound_arg_code(num) {return __unbound_arg_code_arr__[num]}
function save_on_error_code(on_error_code) {__on_error_code_arr__[++__on_error_code_num__] = on_error_code}
function get_on_error_code(num) {return __on_error_code_arr__[num]}
function save_long_name(long_name) {__long_name_arr__[++__long_name_num__] = long_name}
function get_long_name_count() {return __long_name_num__}
function get_long_name(num) {return __long_name_arr__[num]}
function save_short_name(short_name) {__short_name_arr__[++__short_name_num__] = short_name}
function get_short_name(num) {return __short_name_arr__[num]}
function save_takes_args(takes_args) {__takes_args_arr__[++__takes_args_num__] = takes_args}
function get_takes_args(num) {return __takes_args_arr__[num]}
function save_handler_code(handler_code) {__handler_code_arr__[++__handler_code_num__] = handler_code}
function get_handler_code(num) {return __handler_code_arr__[num]}
function save_help_code(help_code) {__help_code_arr__[++__help_code_num__] = help_code}
function get_help_code(num) {return __help_code_arr__[num]}
# </user_utils>

# <user_messages>
function use_str() {
	return sprintf("Use: %s <input-file>", SCRIPT_NAME())
}

function print_use_try() {
	print_puts_err(use_str())
	print_puts_err(sprintf("Try '%s -vHelp=1' for more info", SCRIPT_NAME()))
	exit_failure()
}

function print_version() {
	print_puts(sprintf("%s %s", SCRIPT_NAME(), SCRIPT_VERSION()))
	exit_success()
}

function print_help() {
print sprintf("--- %s %s ---", SCRIPT_NAME(), SCRIPT_VERSION())
print use_str()
print "A line oriented state machine parser."
print ""
print "Options:"
print "-vOutDir=<dir> - set an output directory for the generated *.ic files"
print "-vVersion=1    - print version"
print "-vHelp=1       - print this screen"
print ""
print DESCRIPT_FSM()
	exit_success()
}
# </user_messages>

# <user_code>

function SCRIPT_NAME() {return "parse-opts-gen.awk"}
function SCRIPT_VERSION() {return "2.2"}

function get_cname(name) {
	gsub("-", "_", name)
	return name
}
function get_long_cname(name) {
	return (get_cname(name) "_opt_long")
}
function get_short_cname(name) {
	return (get_cname(name) "_opt_short")
}

function gen_names(opt_num,    long_name, sanitized, ret) {
	long_name = get_long_name(opt_num)

	ret = sprintf("static const char %s = '%s';",
		get_short_cname(long_name), get_short_name(opt_num))
	ret = (ret "\n" sprintf("static const char %s[] = \"%s\";",
		get_long_cname(long_name),
		long_name)\
	)
	ret = (ret "\n")

	return ret
}

function END_CODE() {return "end_code"}

function get_code(    code_str) {
	while ((getline > 0) && (END_CODE() != $1))
		code_str = (code_str $0 "\n")
	return code_str
}

function RET_TYPE() {return "static void"}
function HANDLER_UNBOUND() {return "on_unbound_arg"}
function HANDLER_ERROR() {return "on_error"}

function gen_handler_defn(opt_num,
    title_cmnt, opt_declr, fname, sign, long_name, arg_t, code) {

	long_name = get_long_name(opt_num)
	arg_t = get_context_arg_type(1)
	name = get_cname(long_name)
	title_cmnt = sprintf("// %s", long_name)
	opt_declr = ""
	code = ""

	if (match(long_name, HANDLER_UNBOUND())) {
		code = get_unbound_arg_code(1)
		sign = "const char * arg, void * ctx"
	} else if (match(long_name, HANDLER_ERROR())) {
		code = get_on_error_code(1)
		sign = "opts_err_code err_code, const char * err_opt, void * ctx"
	} else {
		title_cmnt = sprintf("// --%s|-%s", long_name, get_short_name(opt_num))
		code = get_handler_code(opt_num)
		name = sprintf("handle_%s", name)
		sign = "const char * opt, char * opt_arg, void * ctx"
		opt_declr = gen_names(opt_num)
	}

	print_ind_line(title_cmnt)

	if (opt_declr)
		print_ind_str(opt_declr)

	print_ind_line(sprintf("%s %s(%s)", RET_TYPE(), name, sign))

	print_ind_line("{")
	print_ind_str(code)
	print_ind_line("}")
	print_ind_line()
}

function gen_help_defn(opt_num,    long_name) {
	long_name = get_long_name(opt_num)

	print_ind_line(sprintf(\
		"%s help_%s(const char * short_name, const char * long_name)",\
		RET_TYPE(), get_cname(long_name))\
	)
	print_ind_line("{")
	print_ind_str(get_help_code(opt_num))
	print_ind_line("}")
	print_ind_line()
}

function gen_default_handlers() {
	save_long_name("on_unbound_arg")
	gen_handler_defn(get_long_name_count())

	save_long_name("on_error")
	gen_handler_defn(get_long_name_count())
}

function open_tbl() {
	print_ind_line("opts_table the_tbl;")
	print_ind_line("opts_entry all_entries[] = {")
	print_inc_indent()
}

function gen_tbl_entry(opt_num,    ctx, long_name, underscores, short_name) {
	long_name = get_long_name(opt_num)
	ctx = (match(long_name, "^help$")) ? "(&the_tbl)" : get_context_var_name(1)
	short_name = get_short_name(opt_num)

	underscores = get_cname(long_name)
	print_ind_line("{")
	print_inc_indent()
	print_ind_line(".names = {")
		print_inc_indent()
		print_ind_line(sprintf(".long_name = %s,", get_long_cname(long_name)))
		print_ind_line(sprintf(".short_name = %s", get_short_cname(long_name)))
		print_dec_indent()
	print_ind_line("},")
	print_ind_line(".handler = {")
		print_inc_indent()
		print_ind_line(sprintf(".handler = handle_%s,", underscores))
		print_ind_line(sprintf(".context = (void *)%s,", ctx))
		print_dec_indent()
	print_ind_line("},")
	print_ind_line(sprintf(".print_help = help_%s,", underscores))
	print_ind_line(sprintf(".takes_arg = %s,", get_takes_args(opt_num)))
	print_dec_indent()
	print_ind_line("},")
}

function close_tbl(    src) {
	print_dec_indent()
	print_ind_line("};")
	print_ind_line()
	print_ind_line("the_tbl.tbl = all_entries;")
    print_ind_line("the_tbl.length = sizeof(all_entries)/sizeof(*all_entries);")
    print_ind_line()
}

function opts_parse_data() {
	print_ind_line("opts_parse_data parse_data = {")
	print_inc_indent()
	print_ind_line(".the_tbl = &the_tbl,")
	print_ind_line(".on_unbound = {")
		print_inc_indent()
		print_ind_line(sprintf(".handler = %s,", HANDLER_UNBOUND()))
		print_ind_line(sprintf(".context = (void *)%s,",
			get_context_var_name(1)))
		print_dec_indent()
	print_ind_line("},")
	print_ind_line(".on_error = {")
		print_inc_indent()
		print_ind_line(sprintf(".handler = %s,", HANDLER_ERROR()))
		print_ind_line(sprintf(".context = (void *)%s,",
			get_context_var_name(1)))
		print_dec_indent()
	print_ind_line("}")
	print_dec_indent()
	print_ind_line("};")
}

function out_dir_set(out_dir) {_B_out_dir_ = out_dir}
function out_dir_get() {return _B_out_dir_}

function out_file_get(fname,   _out_dir) {
	_out_dir = out_dir_get()
	return _out_dir ? (_out_dir "/" fname) : fname
}

function main(    i, end, opt) {
	end = get_long_name_count()

	print_set_stdout(out_file_get("opts_definitions.ic"))
	print_puts("// <opts_definitions>")
	print_ind_line()
	for (i = 1; i <= end; ++i) {
		gen_handler_defn(i)
		gen_help_defn(i)
	}
	gen_default_handlers()
	print_puts("// </opts_definitions>")

	print_set_stdout(out_file_get("opts_process.ic"))
	print_puts("// <opts_process>")
	open_tbl()
	for (i = 1; i <= end; ++i)
		gen_tbl_entry(i)
	close_tbl()

	opts_parse_data()

	print_ind_line()
	print_ind_line("opts_parse(argc-1, argv+1, &parse_data);")
	print_puts("// </opts_process>")
}

function get_state() {return stm_get_state(_B_the_fsm)}
function transition(st) {stm_next(_B_the_fsm, st)}
# </user_code>

# <awk_loop>
BEGIN {enter()}
END   {leave()}

/^#|^[[:space:]]*$/ {next}
{transition($1); next}
# </awk_loop>
# </other>

# <templated>
# 'foo'# </templated>

# <stm>
# <handlers>
function stm_on_defn_start() {
	if (++_B_defn_start > 1) {
		err_input_quit(\
			sprintf("encountered %s more than once", STM_DEFN_START()))
	}
}
function stm_on_context_arg_type() {
	data_or_err()
	save_context_arg_type($2)
}
function stm_on_context_var_name() {
	data_or_err()
	save_context_var_name($2)
}
function stm_on_unbound_arg_code() {
	save_unbound_arg_code(get_code())
}
function stm_on_on_error_code() {
	save_on_error_code(get_code())
}
function stm_on_long_name(    _name) {
	data_or_err()
	_name = $2
	name_check(_name)
	save_long_name(_name)
}
function stm_on_short_name(    _name) {
	data_or_err()
	_name = $2
	name_check(_name)
	save_short_name(_name)
}
function stm_on_takes_args() {
	data_or_err()
	save_takes_args($2)
}
function stm_on_handler_code() {
	save_handler_code(get_code())
}
function stm_on_help_code() {
	save_help_code(get_code())
}
function stm_on_end() {

}
function stm_on_defn_end() {
	set_can_end()
}
function stm_on_error(curr_st, expected, got) {
	err_quit("line " FNR ": expected " expected ", got " got)
}
# </handlers>

# <constants>
function STM_DEFN_START() {return "defn_start"}
function STM_CONTEXT_ARG_TYPE() {return "context_arg_type"}
function STM_CONTEXT_VAR_NAME() {return "context_var_name"}
function STM_UNBOUND_ARG_CODE() {return "unbound_arg_code"}
function STM_ON_ERROR_CODE() {return "on_error_code"}
function STM_LONG_NAME() {return "long_name"}
function STM_SHORT_NAME() {return "short_name"}
function STM_TAKES_ARGS() {return "takes_args"}
function STM_HANDLER_CODE() {return "handler_code"}
function STM_HELP_CODE() {return "help_code"}
function STM_END() {return "end"}
function STM_DEFN_END() {return "defn_end"}
function _STM_STATE() {return "state"}
# </constants>

# <functions>
function stm_get_state(stm) {return stm[_STM_STATE()]}
function _stm_set_state(stm, next_st) {stm[_STM_STATE()] = next_st}
function stm_next(stm, next_st,    _st) {

	_st = stm_get_state(stm)
	if ("" == _st) {
		if (STM_DEFN_START() == next_st)
		{stm_on_defn_start(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_DEFN_START(), next_st)}
	}
	else if (STM_DEFN_START() == _st) {
		if (STM_CONTEXT_ARG_TYPE() == next_st)
		{stm_on_context_arg_type(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_CONTEXT_ARG_TYPE(), next_st)}
	}
	else if (STM_CONTEXT_ARG_TYPE() == _st) {
		if (STM_CONTEXT_VAR_NAME() == next_st)
		{stm_on_context_var_name(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_CONTEXT_VAR_NAME(), next_st)}
	}
	else if (STM_CONTEXT_VAR_NAME() == _st) {
		if (STM_UNBOUND_ARG_CODE() == next_st)
		{stm_on_unbound_arg_code(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_UNBOUND_ARG_CODE(), next_st)}
	}
	else if (STM_UNBOUND_ARG_CODE() == _st) {
		if (STM_ON_ERROR_CODE() == next_st)
		{stm_on_on_error_code(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_ON_ERROR_CODE(), next_st)}
	}
	else if (STM_ON_ERROR_CODE() == _st) {
		if (STM_LONG_NAME() == next_st)
		{stm_on_long_name(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_LONG_NAME(), next_st)}
	}
	else if (STM_LONG_NAME() == _st) {
		if (STM_SHORT_NAME() == next_st)
		{stm_on_short_name(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_SHORT_NAME(), next_st)}
	}
	else if (STM_SHORT_NAME() == _st) {
		if (STM_TAKES_ARGS() == next_st)
		{stm_on_takes_args(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_TAKES_ARGS(), next_st)}
	}
	else if (STM_TAKES_ARGS() == _st) {
		if (STM_HANDLER_CODE() == next_st)
		{stm_on_handler_code(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_HANDLER_CODE(), next_st)}
	}
	else if (STM_HANDLER_CODE() == _st) {
		if (STM_HELP_CODE() == next_st)
		{stm_on_help_code(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_HELP_CODE(), next_st)}
	}
	else if (STM_HELP_CODE() == _st) {
		if (STM_END() == next_st)
		{stm_on_end(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_END(), next_st)}
	}
	else if (STM_END() == _st) {
		if (STM_LONG_NAME() == next_st)
		{stm_on_long_name(); _stm_set_state(stm, next_st)}
		else if (STM_DEFN_END() == next_st)
		{stm_on_defn_end(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_LONG_NAME()"|"STM_DEFN_END(), next_st)}
	}
	else if (STM_DEFN_END() == _st) {
		if (STM_DEFN_START() == next_st)
		{stm_on_defn_start(); _stm_set_state(stm, next_st)}
		else
		{stm_on_error(_st, STM_DEFN_START(), next_st)}
	}
}
# </functions>
# </stm>

# <includes>
# </includes>
